-- Generated by osi-engine — OSI mapping reference engine
-- Do not edit manually.

BEGIN;

CREATE OR REPLACE FUNCTION _osi_text_norm(j jsonb) RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN
  IF j IS NULL THEN RETURN NULL; END IF;
  CASE jsonb_typeof(j)
    WHEN 'array' THEN
      RETURN COALESCE(
        (SELECT jsonb_agg(_osi_text_norm(elem) ORDER BY idx)
         FROM jsonb_array_elements(j) WITH ORDINALITY AS t(elem, idx)),
        '[]'::jsonb);
    WHEN 'object' THEN
      RETURN COALESCE(
        (SELECT jsonb_object_agg(key, _osi_text_norm(value))
         FROM jsonb_each(j)),
        '{}'::jsonb);
    WHEN 'null' THEN RETURN 'null'::jsonb;
    ELSE RETURN to_jsonb(j #>> '{}');
  END CASE;
END;
$$;

-- Input table: orders
CREATE TABLE IF NOT EXISTS "orders" (
  "_id" numeric,
  "cust_id" TEXT,
  "amount" BIGINT,
  "updated_at" TEXT,
  PRIMARY KEY ("_id")
);

-- Input table: person_with_orders
CREATE TABLE IF NOT EXISTS "person_with_orders" (
  "_id" TEXT,
  "age" BIGINT,
  "type" TEXT,
  "order_count" BIGINT,
  "name" TEXT,
  "orders" JSONB,
  "updated_at" TEXT,
  PRIMARY KEY ("_id")
);

-- Input table: person
CREATE TABLE IF NOT EXISTS "person" (
  "_id" TEXT,
  "age" BIGINT,
  "updated_at" TEXT,
  "name" TEXT,
  PRIMARY KEY ("_id")
);

-- [annotate] _fwd_orders: orders -> global_order
--   _id -> order_id
--   amount -> amount
--   cust_id -> person_ref
-- Forward: orders
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_fwd_orders',
    query => $pgtrickle_q$
SELECT
  "_id"::text AS _src_id,
  'orders'::text AS _mapping,
  NULL::text AS _cluster_id,
  NULL::int AS _priority,
  NULL::text AS _last_modified,
  "_id"::numeric AS "order_id",
  NULL::int AS "_priority_order_id",
  NULL::text AS "_ts_order_id",
  "amount"::numeric AS "amount",
  NULL::int AS "_priority_amount",
  "updated_at" AS "_ts_amount",
  "cust_id"::text AS "person_ref",
  NULL::int AS "_priority_person_ref",
  NULL::text AS "_ts_person_ref",
  jsonb_build_object('_id', "_id", 'amount', "amount", 'cust_id', "cust_id") AS _base
FROM "orders"
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__fwd_orders"
  ON "_fwd_orders" ("_src_id");

-- [annotate] _fwd_person_with_orders_orders: person_with_orders -> global_order
--   order_id -> order_id
--   amount -> amount
--   parent_id -> person_ref
-- Forward: person_with_orders_orders
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_fwd_person_with_orders_orders',
    query => $pgtrickle_q$
SELECT
  "_id"::text AS _src_id,
  'person_with_orders_orders'::text AS _mapping,
  NULL::text AS _cluster_id,
  NULL::int AS _priority,
  "updated_at" AS _last_modified,
  (item.value->>'order_id')::numeric AS "order_id",
  NULL::int AS "_priority_order_id",
  NULL::text AS "_ts_order_id",
  (item.value->>'amount')::numeric AS "amount",
  NULL::int AS "_priority_amount",
  NULL::text AS "_ts_amount",
  "_id"::text AS "person_ref",
  NULL::int AS "_priority_person_ref",
  NULL::text AS "_ts_person_ref",
  jsonb_build_object('order_id', (item.value->>'order_id'), 'amount', (item.value->>'amount'), 'parent_id', "_id") AS _base
FROM "person_with_orders"
CROSS JOIN LATERAL jsonb_array_elements("orders") AS item
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__fwd_person_with_orders_orders"
  ON "_fwd_person_with_orders_orders" ("_src_id", "order_id");

-- [annotate] _fwd_person_with_orders_person: person_with_orders -> global_person
--   _id -> person_id
--   name -> name
--   type -> type
--   age -> age
-- Forward: person_with_orders_person
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_fwd_person_with_orders_person',
    query => $pgtrickle_q$
SELECT
  "_id"::text AS _src_id,
  'person_with_orders_person'::text AS _mapping,
  NULL::text AS _cluster_id,
  NULL::int AS _priority,
  "updated_at" AS _last_modified,
  "_id"::text AS "person_id",
  NULL::int AS "_priority_person_id",
  NULL::text AS "_ts_person_id",
  "type"::text AS "type",
  NULL::int AS "_priority_type",
  NULL::text AS "_ts_type",
  "name"::text AS "name",
  NULL::int AS "_priority_name",
  NULL::text AS "_ts_name",
  upper(("name")) AS "_normalize_name",
  true AS "_has_normalize_name",
  "age"::numeric AS "age",
  NULL::int AS "_priority_age",
  NULL::text AS "_ts_age",
  NULL::numeric AS "order_count",
  NULL::int AS "_priority_order_count",
  NULL::text AS "_ts_order_count",
  jsonb_build_object('_id', "_id", 'name', "name", 'type', "type", 'age', "age", 'order_count', "order_count", 'orders', "orders") AS _base
FROM "person_with_orders"
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__fwd_person_with_orders_person"
  ON "_fwd_person_with_orders_person" ("_src_id");

-- [annotate] _fwd_person: person -> global_person
--   _id -> person_id
--   name -> name
--   age -> age
-- Forward: person
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_fwd_person',
    query => $pgtrickle_q$
SELECT
  "_id"::text AS _src_id,
  'person'::text AS _mapping,
  NULL::text AS _cluster_id,
  NULL::int AS _priority,
  "updated_at" AS _last_modified,
  "_id"::text AS "person_id",
  NULL::int AS "_priority_person_id",
  NULL::text AS "_ts_person_id",
  NULL::text AS "type",
  NULL::int AS "_priority_type",
  NULL::text AS "_ts_type",
  "name"::text AS "name",
  NULL::int AS "_priority_name",
  NULL::text AS "_ts_name",
  upper(("name")) AS "_normalize_name",
  false AS "_has_normalize_name",
  "age"::numeric AS "age",
  NULL::int AS "_priority_age",
  NULL::text AS "_ts_age",
  NULL::numeric AS "order_count",
  NULL::int AS "_priority_order_count",
  NULL::text AS "_ts_order_count",
  jsonb_build_object('_id', "_id", 'name', "name", 'age', "age") AS _base
FROM "person"
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__fwd_person"
  ON "_fwd_person" ("_src_id");

-- [annotate] _id_global_order: identity fields
--   order_id (identity)
--   sources: orders, person_with_orders_orders
--   field: orders: _id -> order_id
--   field: orders: amount -> amount
--   field: orders: cust_id -> person_ref
--   field: person_with_orders_orders: order_id -> order_id
--   field: person_with_orders_orders: amount -> amount
--   field: person_with_orders_orders: parent_id -> person_ref
-- Identity: global_order
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_id_global_order',
    query => $pgtrickle_q$
WITH RECURSIVE _id_base AS (
  SELECT _src_id, _mapping, _cluster_id, _priority, _last_modified, "order_id", "_priority_order_id", "_ts_order_id", "amount", "_priority_amount", "_ts_amount", "person_ref", "_priority_person_ref", "_ts_person_ref", _base FROM "_fwd_orders"
  UNION ALL
  SELECT _src_id, _mapping, _cluster_id, _priority, _last_modified, "order_id", "_priority_order_id", "_ts_order_id", "amount", "_priority_amount", "_ts_amount", "person_ref", "_priority_person_ref", "_ts_person_ref", _base FROM "_fwd_person_with_orders_orders"
),
_id_numbered AS (
  SELECT *, md5(_mapping || ':' || _src_id || ':' || COALESCE("order_id"::text, '')) AS _entity_id
  FROM _id_base
),
_id_closure AS (
  SELECT _entity_id, _entity_id AS _component
  FROM _id_numbered
  UNION
  SELECT n._entity_id, c._component
  FROM _id_closure c
  JOIN _id_numbered n2 ON c._entity_id = n2._entity_id
  JOIN _id_numbered n ON n._entity_id <> n2._entity_id
    AND ((n."order_id" IS NOT NULL AND n."order_id" = n2."order_id"))
  WHERE c._component < n._entity_id
),
_id_final AS (
  SELECT _entity_id, MIN(_component) AS _entity_id_resolved
  FROM _id_closure
  GROUP BY _entity_id
)
SELECT n._src_id, n._mapping, n._cluster_id, n._priority, n._last_modified, n."order_id", n."_priority_order_id", n."_ts_order_id", n."amount", n."_priority_amount", n."_ts_amount", n."person_ref", n."_priority_person_ref", n."_ts_person_ref", n._base, n._entity_id, f._entity_id_resolved
FROM _id_numbered n
JOIN _id_final f ON n._entity_id = f._entity_id
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__id_global_order"
  ON "_id_global_order" ("_entity_id");

-- [annotate] _id_global_person: identity fields
--   person_id (identity)
--   sources: person, person_with_orders_person
--   field: person: _id -> person_id
--   field: person: name -> name
--   field: person: age -> age
--   field: person_with_orders_person: _id -> person_id
--   field: person_with_orders_person: name -> name
--   field: person_with_orders_person: type -> type
--   field: person_with_orders_person: age -> age
-- Identity: global_person
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_id_global_person',
    query => $pgtrickle_q$
WITH RECURSIVE _id_base AS (
  SELECT _src_id, _mapping, _cluster_id, _priority, _last_modified, "person_id", "_priority_person_id", "_ts_person_id", "type", "_priority_type", "_ts_type", "name", "_priority_name", "_ts_name", "_normalize_name", "_has_normalize_name", "age", "_priority_age", "_ts_age", "order_count", "_priority_order_count", "_ts_order_count", _base FROM "_fwd_person"
  UNION ALL
  SELECT _src_id, _mapping, _cluster_id, _priority, _last_modified, "person_id", "_priority_person_id", "_ts_person_id", "type", "_priority_type", "_ts_type", "name", "_priority_name", "_ts_name", "_normalize_name", "_has_normalize_name", "age", "_priority_age", "_ts_age", "order_count", "_priority_order_count", "_ts_order_count", _base FROM "_fwd_person_with_orders_person"
),
_id_numbered AS (
  SELECT *, md5(_mapping || ':' || _src_id || ':' || COALESCE("person_id"::text, '')) AS _entity_id
  FROM _id_base
),
_id_closure AS (
  SELECT _entity_id, _entity_id AS _component
  FROM _id_numbered
  UNION
  SELECT n._entity_id, c._component
  FROM _id_closure c
  JOIN _id_numbered n2 ON c._entity_id = n2._entity_id
  JOIN _id_numbered n ON n._entity_id <> n2._entity_id
    AND ((n."person_id" IS NOT NULL AND n."person_id" = n2."person_id"))
  WHERE c._component < n._entity_id
),
_id_final AS (
  SELECT _entity_id, MIN(_component) AS _entity_id_resolved
  FROM _id_closure
  GROUP BY _entity_id
)
SELECT n._src_id, n._mapping, n._cluster_id, n._priority, n._last_modified, n."person_id", n."_priority_person_id", n."_ts_person_id", n."type", n."_priority_type", n."_ts_type", n."name", n."_priority_name", n."_ts_name", n."_normalize_name", n."_has_normalize_name", n."age", n."_priority_age", n."_ts_age", n."order_count", n."_priority_order_count", n."_ts_order_count", n._base, n._entity_id, f._entity_id_resolved
FROM _id_numbered n
JOIN _id_final f ON n._entity_id = f._entity_id
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__id_global_person"
  ON "_id_global_person" ("_entity_id");

-- [annotate] resolution strategies:
--   order_id: identity
--   amount: lastmodified
--   person_ref: coalesce
-- Resolution: global_order
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_resolved_global_order',
    query => $pgtrickle_q$
SELECT
  _entity_id_resolved AS _entity_id,
  min("order_id") AS "order_id",
  (array_agg("amount" ORDER BY COALESCE("_ts_amount", _last_modified) DESC NULLS LAST) FILTER (WHERE "amount" IS NOT NULL))[1] AS "amount",
  (array_agg("person_ref" ORDER BY 0 ASC, COALESCE("_priority_person_ref", _priority, 999) ASC NULLS LAST) FILTER (WHERE "person_ref" IS NOT NULL))[1] AS "person_ref"
FROM "_id_global_order"
GROUP BY _entity_id_resolved
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__resolved_global_order"
  ON "_resolved_global_order" ("_entity_id");

-- [annotate] resolution strategies:
--   person_id: identity
--   type: coalesce
--   name: lastmodified
--   age: lastmodified
--   order_count: COALESCE((
--     SELECT count(*)
--     FROM global_order o
--     WHERE o.person_ref = global_person.person_id
--   ), 0)
-- Resolution: global_person
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_resolved_global_person',
    query => $pgtrickle_q$
WITH
  "_echo" AS (
    SELECT *,
      ROW_NUMBER() OVER (
        PARTITION BY _entity_id_resolved, "_normalize_name"
        ORDER BY "_has_normalize_name" ASC, COALESCE("_ts_name", _last_modified) DESC NULLS LAST
      ) AS "_echo_rank_name"
    FROM "_id_global_person"
  )
SELECT
  _entity_id_resolved AS _entity_id,
  min("person_id") AS "person_id",
  (array_agg("type" ORDER BY 0 ASC, COALESCE("_priority_type", _priority, 999) ASC NULLS LAST) FILTER (WHERE "type" IS NOT NULL))[1] AS "type",
  (array_agg("name" ORDER BY COALESCE("_ts_name", _last_modified) DESC NULLS LAST) FILTER (WHERE "name" IS NOT NULL AND "_echo_rank_name" = 1))[1] AS "name",
  (array_agg("age" ORDER BY COALESCE("_ts_age", _last_modified) DESC NULLS LAST) FILTER (WHERE "age" IS NOT NULL))[1] AS "age"
FROM "_echo"
GROUP BY _entity_id_resolved
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__resolved_global_person"
  ON "_resolved_global_person" ("_entity_id");

-- global_order
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => 'global_order',
    query => $pgtrickle_q$
SELECT
  _entity_id AS _cluster_id,
  "order_id",
  "amount",
  "person_ref"
FROM "_resolved_global_order"
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_global_order"
  ON "global_order" ("_cluster_id");

-- [annotate] _rev_orders: reverse projection
--   field: order_id -> _id
--   field: amount -> amount
--   field: person_ref -> cust_id
-- Reverse: orders (global_order → orders)
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_rev_orders',
    query => $pgtrickle_q$
SELECT
  id._src_id,
  COALESCE(id._entity_id_resolved, r._entity_id) AS _cluster_id,
  COALESCE(id._src_id::numeric, COALESCE(id."order_id", r."order_id")) AS "_id",
  NULLIF(to_jsonb(r)->>'_order_rank_order_id', '')::bigint AS "_order_rank__id",
  r."amount" AS "amount",
  NULLIF(to_jsonb(r)->>'_order_rank_amount', '')::bigint AS "_order_rank_amount",
  COALESCE((SELECT ref_local._src_id FROM "_id_global_person" ref_match JOIN "_id_global_person" ref_local ON ref_local._entity_id_resolved = ref_match._entity_id_resolved WHERE ref_match._src_id = r."person_ref"::text AND ref_local._mapping = 'person' AND ref_local._src_id::text = id._base->>'cust_id' LIMIT 1), (SELECT ref_local._src_id FROM "_id_global_person" ref_match JOIN "_id_global_person" ref_local ON ref_local._entity_id_resolved = ref_match._entity_id_resolved WHERE (ref_match._src_id = r."person_ref"::text OR ref_match."person_id"::text = r."person_ref"::text) AND ref_local._mapping = 'person' LIMIT 1)) AS "cust_id",
  NULLIF(to_jsonb(r)->>'_order_rank_person_ref', '')::bigint AS "_order_rank_cust_id",
  id._base
FROM "_resolved_global_order" AS r
LEFT JOIN (SELECT _src_id, _mapping, _entity_id_resolved, _base, "order_id" FROM "_id_global_order") AS id
  ON id._entity_id_resolved = r._entity_id
    AND id._mapping = 'orders'
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__rev_orders"
  ON "_rev_orders" ("_cluster_id", "_src_id")
  NULLS NOT DISTINCT;

-- [annotate] _rev_person_with_orders_orders: reverse projection
--   field: order_id -> order_id
--   field: amount -> amount
--   field: person_ref -> parent_id
--   reverse_filter: amount > 100
-- Reverse: person_with_orders_orders (global_order → person_with_orders)
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_rev_person_with_orders_orders',
    query => $pgtrickle_q$
SELECT
  id._src_id,
  COALESCE(id._entity_id_resolved, r._entity_id) AS _cluster_id,
  id._src_id AS "_id",
  COALESCE(id."order_id", r."order_id") AS "order_id",
  NULLIF(to_jsonb(r)->>'_order_rank_order_id', '')::bigint AS "_order_rank_order_id",
  r."amount" AS "amount",
  NULLIF(to_jsonb(r)->>'_order_rank_amount', '')::bigint AS "_order_rank_amount",
  COALESCE(COALESCE((SELECT ref_local._src_id FROM "_id_global_person" ref_match JOIN "_id_global_person" ref_local ON ref_local._entity_id_resolved = ref_match._entity_id_resolved WHERE ref_match._src_id = r."person_ref"::text AND ref_local._mapping = 'person_with_orders_person' AND ref_local._src_id::text = id._base->>'parent_id' LIMIT 1), (SELECT ref_local._src_id FROM "_id_global_person" ref_match JOIN "_id_global_person" ref_local ON ref_local._entity_id_resolved = ref_match._entity_id_resolved WHERE (ref_match._src_id = r."person_ref"::text OR ref_match."person_id"::text = r."person_ref"::text) AND ref_local._mapping = 'person_with_orders_person' LIMIT 1)), (SELECT ref_fb._entity_id_resolved FROM "_id_global_person" ref_fb WHERE (ref_fb._src_id = r."person_ref"::text OR ref_fb."person_id"::text = r."person_ref"::text) LIMIT 1)) AS "parent_id",
  NULLIF(to_jsonb(r)->>'_order_rank_person_ref', '')::bigint AS "_order_rank_parent_id",
  id._base
FROM "_resolved_global_order" AS r
LEFT JOIN (SELECT _src_id, _mapping, _entity_id_resolved, _base, "order_id" FROM "_id_global_order") AS id
  ON id._entity_id_resolved = r._entity_id
    AND id._mapping = 'person_with_orders_orders'
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__rev_person_with_orders_orders"
  ON "_rev_person_with_orders_orders" ("_cluster_id", "_src_id")
  NULLS NOT DISTINCT;

-- Enriched: global_person
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_enriched_global_person',
    query => $pgtrickle_q$
SELECT
  global_person._entity_id,
  global_person."person_id",
  global_person."type",
  global_person."name",
  global_person."age",
  "_lat_order_count".val AS "order_count"
FROM "_resolved_global_person" global_person
LEFT JOIN LATERAL (
  SELECT (COALESCE((
  SELECT count(*)
  FROM "_resolved_global_order" o
  WHERE o.person_ref = global_person.person_id
), 0)) AS val
) "_lat_order_count" ON true
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__enriched_global_person"
  ON "_enriched_global_person" ("_entity_id");

-- Delta for source: orders
-- Delta: orders (change detection)
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_delta_orders',
    query => $pgtrickle_q$
SELECT
  CASE
      WHEN _src_id IS NULL THEN 'insert'
      WHEN _base->>'amount' IS NOT DISTINCT FROM "amount"::text AND _base->>'cust_id' IS NOT DISTINCT FROM "cust_id"::text THEN 'noop'
      ELSE 'update'
    END AS _action,
  "_cluster_id",
  "_id",
  "amount",
  "cust_id",
  "_base"
FROM "_rev_orders"
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__delta_orders"
  ON "_delta_orders" ("_cluster_id", "_id")
  NULLS NOT DISTINCT;

-- global_person
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => 'global_person',
    query => $pgtrickle_q$
SELECT
  _entity_id AS _cluster_id,
  "person_id",
  "type",
  "name",
  "age",
  "order_count"
FROM "_enriched_global_person"
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_global_person"
  ON "global_person" ("_cluster_id");

-- [annotate] _rev_person: reverse projection
--   field: person_id -> _id
--   field: name -> name
--   field: age -> age
-- Reverse: person (global_person → person)
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_rev_person',
    query => $pgtrickle_q$
SELECT
  id._src_id,
  COALESCE(id._entity_id_resolved, r._entity_id) AS _cluster_id,
  COALESCE(id._src_id, COALESCE(id."person_id", r."person_id")) AS "_id",
  NULLIF(to_jsonb(r)->>'_order_rank_person_id', '')::bigint AS "_order_rank__id",
  r."name" AS "name",
  NULLIF(to_jsonb(r)->>'_order_rank_name', '')::bigint AS "_order_rank_name",
  r."age" AS "age",
  NULLIF(to_jsonb(r)->>'_order_rank_age', '')::bigint AS "_order_rank_age",
  id._base
FROM "_enriched_global_person" AS r
LEFT JOIN (SELECT _src_id, _mapping, _entity_id_resolved, _base, "person_id" FROM "_id_global_person") AS id
  ON id._entity_id_resolved = r._entity_id
    AND id._mapping = 'person'
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__rev_person"
  ON "_rev_person" ("_cluster_id", "_src_id")
  NULLS NOT DISTINCT;

-- [annotate] _rev_person_with_orders_person: reverse projection
--   field: person_id -> _id
--   field: name -> name, reverse_expression: upper(name)
--   field: type -> type, reverse_expression: 'customer'
--   field: age -> age
--   field: order_count -> order_count
-- Reverse: person_with_orders_person (global_person → person_with_orders)
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_rev_person_with_orders_person',
    query => $pgtrickle_q$
SELECT
  id._src_id,
  COALESCE(id._entity_id_resolved, r._entity_id) AS _cluster_id,
  COALESCE(id._src_id, COALESCE(id."person_id", r."person_id")) AS "_id",
  NULLIF(to_jsonb(r)->>'_order_rank_person_id', '')::bigint AS "_order_rank__id",
  upper(name) AS "name",
  NULLIF(to_jsonb(r)->>'_order_rank_name', '')::bigint AS "_order_rank_name",
  'customer' AS "type",
  NULLIF(to_jsonb(r)->>'_order_rank_type', '')::bigint AS "_order_rank_type",
  r."age" AS "age",
  NULLIF(to_jsonb(r)->>'_order_rank_age', '')::bigint AS "_order_rank_age",
  r."order_count" AS "order_count",
  NULLIF(to_jsonb(r)->>'_order_rank_order_count', '')::bigint AS "_order_rank_order_count",
  id._base
FROM "_enriched_global_person" AS r
LEFT JOIN (SELECT _src_id, _mapping, _entity_id_resolved, _base, "person_id" FROM "_id_global_person") AS id
  ON id._entity_id_resolved = r._entity_id
    AND id._mapping = 'person_with_orders_person'
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__rev_person_with_orders_person"
  ON "_rev_person_with_orders_person" ("_cluster_id", "_src_id")
  NULLS NOT DISTINCT;

-- Delta for source: person
-- Delta: person (change detection)
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_delta_person',
    query => $pgtrickle_q$
SELECT
  CASE
      WHEN _src_id IS NULL THEN 'insert'
      WHEN _base->>'name' IS NOT DISTINCT FROM "name"::text AND _base->>'age' IS NOT DISTINCT FROM "age"::text THEN 'noop'
      ELSE 'update'
    END AS _action,
  "_cluster_id",
  "_id",
  "name",
  "age",
  "_base"
FROM "_rev_person"
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__delta_person"
  ON "_delta_person" ("_cluster_id", "_id")
  NULLS NOT DISTINCT;

-- Delta for source: person_with_orders
-- Delta: person_with_orders (change detection)
SELECT pgtrickle.create_stream_table_if_not_exists(
    name => '_delta_person_with_orders',
    query => $pgtrickle_q$
WITH _nested_orders AS (
SELECT n."parent_id" AS _parent_key, COALESCE(jsonb_agg(jsonb_build_object('order_id', n."order_id", 'amount', n."amount") ORDER BY n."amount" DESC NULLS LAST, n."order_id"), '[]'::jsonb) AS "orders"
FROM "_rev_person_with_orders_orders" AS n
WHERE n."parent_id" IS NOT NULL AND NOT (n."order_id" IS NULL AND n."amount" IS NULL)
GROUP BY n."parent_id"
)
SELECT
  CASE
      WHEN p._src_id IS NULL THEN 'insert'
      WHEN p._base->>'name' IS NOT DISTINCT FROM p."name"::text AND p._base->>'type' IS NOT DISTINCT FROM p."type"::text AND p._base->>'age' IS NOT DISTINCT FROM p."age"::text AND COALESCE(_osi_text_norm(p._base->'orders')::text, '[]') IS NOT DISTINCT FROM COALESCE(_osi_text_norm(_nested_orders."orders")::text, '[]') THEN 'noop'
      ELSE 'update'
    END AS _action,
  p."_cluster_id",
  p."_id",
  p."name",
  p."type",
  p."age",
  p."order_count",
  COALESCE(_nested_orders."orders", '[]'::jsonb) AS "orders",
  p."_base"
FROM "_rev_person_with_orders_person" AS p
LEFT JOIN _nested_orders ON _nested_orders._parent_key = CASE WHEN p._src_id IS NULL THEN p."_cluster_id" ELSE p."_id"::text END
$pgtrickle_q$
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx__delta_person_with_orders"
  ON "_delta_person_with_orders" ("_cluster_id", "_id")
  NULLS NOT DISTINCT;

-- Refresh materialized views in dependency order
SELECT pgtrickle.refresh_stream_table('_fwd_orders');
SELECT pgtrickle.refresh_stream_table('_fwd_person_with_orders_orders');
SELECT pgtrickle.refresh_stream_table('_fwd_person_with_orders_person');
SELECT pgtrickle.refresh_stream_table('_fwd_person');
SELECT pgtrickle.refresh_stream_table('_id_global_order');
SELECT pgtrickle.refresh_stream_table('_id_global_person');
SELECT pgtrickle.refresh_stream_table('_resolved_global_order');
SELECT pgtrickle.refresh_stream_table('_resolved_global_person');
SELECT pgtrickle.refresh_stream_table('global_order');
SELECT pgtrickle.refresh_stream_table('_rev_orders');
SELECT pgtrickle.refresh_stream_table('_rev_person_with_orders_orders');
SELECT pgtrickle.refresh_stream_table('_enriched_global_person');
SELECT pgtrickle.refresh_stream_table('_delta_orders');
SELECT pgtrickle.refresh_stream_table('global_person');
SELECT pgtrickle.refresh_stream_table('_rev_person');
SELECT pgtrickle.refresh_stream_table('_rev_person_with_orders_person');
SELECT pgtrickle.refresh_stream_table('_delta_person');
SELECT pgtrickle.refresh_stream_table('_delta_person_with_orders');

COMMIT;
